---
- name: Common
  hosts: "fs-servicos"
  remote_user: ansible
  become: true
  roles:
    - firewalld
  environment: "{{ proxy_env }}"
  tags:
    - common


- name: FTP Server - Service
  hosts: "fs-servicos"
  remote_user: ansible
  become: true
  roles:
    - vsftpd-server
    - ftp-users
    - mount
  environment: "{{ proxy_env }}"
  tags:
    - ftp


- name: Minio - Object Storage
  hosts: "fs-servicos"
  remote_user: ansible
  become: true
  roles:
    - { role: docker-ce, when: deploy_docker }
    - minio-nginx
  environment: "{{proxy_env}}"
  tags:
    - minio-nginx
