---
- name: Common
  hosts: all
  remote_user: centos
  become: true
  roles:
    - firewalld
  environment: "{{ proxy_env }}"
  tags:
    - common

- name: Minio - Object Storage
  hosts: all
  remote_user: centos
  become: true
  roles:
    - { role: docker-ce, when: deploy_docker }
    - minio-nginx
  environment: "{{proxy_env}}"
  tags:
    - minio-nginx
