---
- name: mount | target
  mount:
    state: mounted
    fstype: cifs
    opts: "domain=TRT4,username=target,password=T3rr42012$$..,uid={{ ftp_users['target'].uid }},gid={{ ftp_users['target'].uid }},forceuid,forcegid"
    src: "//windows/target"
    name: "{{ minio_instances['target'].data_dir }}"
