---
- name: minio | target
  mount:
    state: mounted
    fstype: cifs
    opts: "domain=TRT4,username=target,password=T3rr42012$$.."
    src: "//windows/target"
    name: "{{ minio_instances['target'].data_dir }}"
